Auto merge workflow.

diff --git a/.github/workflows/validation.yml b/.github/workflows/validation.yml
--- a/.github/workflows/validation.yml
+++ b/.github/workflows/validation.yml
@@ -1,6 +1,9 @@
 name: Coding Standards
 
 on:
+  push:
+    branches-ignore:
+      - 'main'
   pull_request:
     paths-ignore:
       - "**/includes/**"
@@ -14,16 +17,27 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checking out code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
         with:
           fetch-depth: 0 # 0 indicates all history for all branches and tags.
 
       # Need to install Composer to be able to add the coding standards rules.
       - name: Installing Composer
         run: |
+          EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
           php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
-          php composer-setup.php
-          php -r "unlink('composer-setup.php');"
+          ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
+
+          if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]
+          then
+              >&2 echo 'ERROR: Invalid installer checksum'
+              rm composer-setup.php
+              exit 1
+          fi
+          php composer-setup.php --quiet
+          RESULT=$?
+          rm composer-setup.php
+          exit $RESULT
 
       - name: Downloading and installing PHP_CodeSniffer and the Drupal coding standards rules
         run: |
@@ -34,7 +48,7 @@ jobs:
       - name: Checking coding standards
         uses: thenabeel/action-phpcs@v8
         with:
-          files: "**.inc,**.install,**.module,**.php,**.profile,**.theme"
+          files: "**.inc,**.install,**.md,**.module,**.php,**.profile,**.test,**.txt,**.theme,**.yml"
           phpcs_path: $HOME/.composer/vendor/bin/phpcs
           standard: phpcs.xml
           scope: files
